/** @format */

export const data = [
  {
    numberOfProjects: 18,
    projectManager: "Alice Smith",
    totalProjectValue: 9000,
    totalReleasedAmount: 7500,
    numberOfFullyCompletedProjects: 14,
    numberOfCompletedProjectsWithoutAuthorization: 1,
    projectCompletionRate: 88,
    projectCompletionRateWithoutAuthorization: 75,
    numberOfFirstTimeClients: 10,
    milestoneCompletionRate: 92,
    taskCompletionRate: 89,
    averageProjectCompletionTime: 22,
    numberOfUpsaleCrossSales: 4,
    valueOfUpsaleCrossSales: 2500,
    canceledProjects: 1,
    delayedProjects: 2,
    delayedCompleted: 0,
    percentageOfDelayedProjects: 20,
    cancelationRate: 5,
    averagePaymentReleaseTime: 6,
  },
  {
    numberOfProjects: 20,
    projectManager: "Bob Johnson",
    totalProjectValue: 11000,
    totalReleasedAmount: 9000,
    numberOfFullyCompletedProjects: 18,
    numberOfCompletedProjectsWithoutAuthorization: 0,
    projectCompletionRate: 95,
    projectCompletionRateWithoutAuthorization: 0,
    numberOfFirstTimeClients: 12,
    milestoneCompletionRate: 98,
    taskCompletionRate: 91,
    averageProjectCompletionTime: 21,
    numberOfUpsaleCrossSales: 6,
    valueOfUpsaleCrossSales: 4000,
    canceledProjects: 0,
    delayedProjects: 1,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 10,
    cancelationRate: 0,
    averagePaymentReleaseTime: 5,
  },
  {
    numberOfProjects: 15,
    projectManager: "Charlie Brown",
    totalProjectValue: 8500,
    totalReleasedAmount: 7000,
    numberOfFullyCompletedProjects: 12,
    numberOfCompletedProjectsWithoutAuthorization: 2,
    projectCompletionRate: 80,
    projectCompletionRateWithoutAuthorization: 70,
    numberOfFirstTimeClients: 7,
    milestoneCompletionRate: 88,
    taskCompletionRate: 85,
    averageProjectCompletionTime: 24,
    numberOfUpsaleCrossSales: 3,
    valueOfUpsaleCrossSales: 2000,
    canceledProjects: 3,
    delayedProjects: 4,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 30,
    cancelationRate: 15,
    averagePaymentReleaseTime: 8,
  },

  // Object 2
  {
    numberOfProjects: 22,
    projectManager: "David Davis",
    totalProjectValue: 9500,
    totalReleasedAmount: 8000,
    numberOfFullyCompletedProjects: 19,
    numberOfCompletedProjectsWithoutAuthorization: 1,
    projectCompletionRate: 86,
    projectCompletionRateWithoutAuthorization: 78,
    numberOfFirstTimeClients: 11,
    milestoneCompletionRate: 93,
    taskCompletionRate: 90,
    averageProjectCompletionTime: 20,
    numberOfUpsaleCrossSales: 5,
    valueOfUpsaleCrossSales: 3000,
    canceledProjects: 2,
    delayedProjects: 2,
    delayedCompleted: 0,
    percentageOfDelayedProjects: 15,
    cancelationRate: 10,
    averagePaymentReleaseTime: 7,
  },
  {
    numberOfProjects: 25,
    projectManager: "Eva Evans",
    totalProjectValue: 12000,
    totalReleasedAmount: 10000,
    numberOfFullyCompletedProjects: 21,
    numberOfCompletedProjectsWithoutAuthorization: 2,
    projectCompletionRate: 92,
    projectCompletionRateWithoutAuthorization: 85,
    numberOfFirstTimeClients: 14,
    milestoneCompletionRate: 96,
    taskCompletionRate: 88,
    averageProjectCompletionTime: 18,
    numberOfUpsaleCrossSales: 7,
    valueOfUpsaleCrossSales: 5000,
    canceledProjects: 1,
    delayedProjects: 3,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 12,
    cancelationRate: 5,
    averagePaymentReleaseTime: 6,
  },

  // Object 4
  {
    numberOfProjects: 19,
    projectManager: "Frankie Franklin",
    totalProjectValue: 9000,
    totalReleasedAmount: 7500,
    numberOfFullyCompletedProjects: 16,
    numberOfCompletedProjectsWithoutAuthorization: 0,
    projectCompletionRate: 84,
    projectCompletionRateWithoutAuthorization: 0,
    numberOfFirstTimeClients: 9,
    milestoneCompletionRate: 89,
    taskCompletionRate: 82,
    averageProjectCompletionTime: 23,
    numberOfUpsaleCrossSales: 4,
    valueOfUpsaleCrossSales: 2500,
    canceledProjects: 2,
    delayedProjects: 2,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 15,
    cancelationRate: 10,
    averagePaymentReleaseTime: 7,
  },
];
