/** @format */

export const data = [
  {
    numberOfProjects: 18,
    projectManager: "Alice Smith",
    totalProjectValue: 9000,
    totalReleasedAmount: 7500,
    numberOfFullyCompletedProjects: 14,
    numberOfCompletedProjectsWithoutAuthorization: 1,
    projectCompletionRate: 88,
    projectCompletionRateWithoutAuthorization: 75,
    numberOfFirstTimeClients: 10,
    milestoneCompletionRate: 92,
    taskCompletionRate: 89,
    averageProjectCompletionTime: 22,
    numberOfUpsaleCrossSales: 4,
    valueOfUpsaleCrossSales: 2500,
    canceledProjects: 1,
    delayedProjects: 2,
    delayedCompleted: 0,
    percentageOfDelayedProjects: 20,
    cancelationRate: 5,
    averagePaymentReleaseTime: 6,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },

  {
    numberOfProjects: 20,
    projectManager: "Bob Johnson",
    totalProjectValue: 11000,
    totalReleasedAmount: 9000,
    numberOfFullyCompletedProjects: 18,
    numberOfCompletedProjectsWithoutAuthorization: 0,
    projectCompletionRate: 95,
    projectCompletionRateWithoutAuthorization: 0,
    numberOfFirstTimeClients: 12,
    milestoneCompletionRate: 98,
    taskCompletionRate: 91,
    averageProjectCompletionTime: 21,
    numberOfUpsaleCrossSales: 6,
    valueOfUpsaleCrossSales: 4000,
    canceledProjects: 0,
    delayedProjects: 1,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 10,
    cancelationRate: 0,
    averagePaymentReleaseTime: 5,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },
  {
    numberOfProjects: 15,
    projectManager: "Charlie Brown",
    totalProjectValue: 8500,
    totalReleasedAmount: 7000,
    numberOfFullyCompletedProjects: 12,
    numberOfCompletedProjectsWithoutAuthorization: 2,
    projectCompletionRate: 80,
    projectCompletionRateWithoutAuthorization: 70,
    numberOfFirstTimeClients: 7,
    milestoneCompletionRate: 88,
    taskCompletionRate: 85,
    averageProjectCompletionTime: 24,
    numberOfUpsaleCrossSales: 3,
    valueOfUpsaleCrossSales: 2000,
    canceledProjects: 3,
    delayedProjects: 4,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 30,
    cancelationRate: 15,
    averagePaymentReleaseTime: 8,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },

  // Object 2
  {
    numberOfProjects: 22,
    projectManager: "David Davis",
    totalProjectValue: 9500,
    totalReleasedAmount: 8000,
    numberOfFullyCompletedProjects: 19,
    numberOfCompletedProjectsWithoutAuthorization: 1,
    projectCompletionRate: 86,
    projectCompletionRateWithoutAuthorization: 78,
    numberOfFirstTimeClients: 11,
    milestoneCompletionRate: 93,
    taskCompletionRate: 90,
    averageProjectCompletionTime: 20,
    numberOfUpsaleCrossSales: 5,
    valueOfUpsaleCrossSales: 3000,
    canceledProjects: 2,
    delayedProjects: 2,
    delayedCompleted: 0,
    percentageOfDelayedProjects: 15,
    cancelationRate: 10,
    averagePaymentReleaseTime: 7,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },
  {
    numberOfProjects: 25,
    projectManager: "Eva Evans",
    totalProjectValue: 12000,
    totalReleasedAmount: 10000,
    numberOfFullyCompletedProjects: 21,
    numberOfCompletedProjectsWithoutAuthorization: 2,
    projectCompletionRate: 92,
    projectCompletionRateWithoutAuthorization: 85,
    numberOfFirstTimeClients: 14,
    milestoneCompletionRate: 96,
    taskCompletionRate: 88,
    averageProjectCompletionTime: 18,
    numberOfUpsaleCrossSales: 7,
    valueOfUpsaleCrossSales: 5000,
    canceledProjects: 1,
    delayedProjects: 3,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 12,
    cancelationRate: 5,
    averagePaymentReleaseTime: 6,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },

  // Object 4
  {
    numberOfProjects: 19,
    projectManager: "Frankie Franklin",
    totalProjectValue: 9000,
    totalReleasedAmount: 7500,
    numberOfFullyCompletedProjects: 16,
    numberOfCompletedProjectsWithoutAuthorization: 0,
    projectCompletionRate: 84,
    projectCompletionRateWithoutAuthorization: 0,
    numberOfFirstTimeClients: 9,
    milestoneCompletionRate: 89,
    taskCompletionRate: 82,
    averageProjectCompletionTime: 23,
    numberOfUpsaleCrossSales: 4,
    valueOfUpsaleCrossSales: 2500,
    canceledProjects: 2,
    delayedProjects: 2,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 15,
    cancelationRate: 10,
    averagePaymentReleaseTime: 7,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },
  {
    numberOfProjects: 22,
    projectManager: "Grace Green",
    totalProjectValue: 11000,
    totalReleasedAmount: 9000,
    numberOfFullyCompletedProjects: 20,
    numberOfCompletedProjectsWithoutAuthorization: 1,
    projectCompletionRate: 91,
    projectCompletionRateWithoutAuthorization: 80,
    numberOfFirstTimeClients: 12,
    milestoneCompletionRate: 95,
    taskCompletionRate: 88,
    averageProjectCompletionTime: 20,
    numberOfUpsaleCrossSales: 5,
    valueOfUpsaleCrossSales: 3000,
    canceledProjects: 1,
    delayedProjects: 1,
    delayedCompleted: 0,
    percentageOfDelayedProjects: 10,
    cancelationRate: 5,
    averagePaymentReleaseTime: 6,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },
  {
    numberOfProjects: 25,
    projectManager: "George Goodman",
    totalProjectValue: 12000,
    totalReleasedAmount: 10000,
    numberOfFullyCompletedProjects: 22,
    numberOfCompletedProjectsWithoutAuthorization: 2,
    projectCompletionRate: 88,
    projectCompletionRateWithoutAuthorization: 75,
    numberOfFirstTimeClients: 15,
    milestoneCompletionRate: 92,
    taskCompletionRate: 85,
    averageProjectCompletionTime: 18,
    numberOfUpsaleCrossSales: 7,
    valueOfUpsaleCrossSales: 4500,
    canceledProjects: 0,
    delayedProjects: 3,
    delayedCompleted: 1,
    percentageOfDelayedProjects: 12,
    cancelationRate: 0,
    averagePaymentReleaseTime: 5,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },
  {
    numberOfProjects: 18,
    projectManager: "Holly Harper",
    totalProjectValue: 8000,
    totalReleasedAmount: 6800,
    numberOfFullyCompletedProjects: 15,
    numberOfCompletedProjectsWithoutAuthorization: 1,
    projectCompletionRate: 82,
    projectCompletionRateWithoutAuthorization: 70,
    numberOfFirstTimeClients: 8,
    milestoneCompletionRate: 87,
    taskCompletionRate: 80,
    averageProjectCompletionTime: 25,
    numberOfUpsaleCrossSales: 3,
    valueOfUpsaleCrossSales: 2000,
    canceledProjects: 1,
    delayedProjects: 4,
    delayedCompleted: 2,
    percentageOfDelayedProjects: 22,
    cancelationRate: 5,
    averagePaymentReleaseTime: 8,
    projectsDetails: [
      {
        slNo: 1,
        client: "Client A",
        projectName: "Project Alpha",
        projectValue: 500,
        dealClosedBy: "Bob Johnson",
        estimatedHours: 40,
        totalHoursLog: 35,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/alpha",
        freelanceComProfileLink: "https://www.freelancer.com/u/bobjohnson",
        members: ["Alice Smith", "Bob Johnson", "Charlie Brown"],
        startDate: "2023-01-01",
      },
      {
        slNo: 2,
        client: "Client B",
        projectName: "Project Beta",
        projectValue: 800,
        dealClosedBy: "Alice Smith",
        estimatedHours: 60,
        totalHoursLog: 45,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/beta",
        freelanceComProfileLink: "https://www.freelancer.com/u/alicesmith",
        members: ["Alice Smith", "David White", "Eva Green"],
        startDate: "2023-02-15",
      },
      {
        slNo: 3,
        client: "Client C",
        projectName: "Project Gamma",
        projectValue: 1200,
        dealClosedBy: "Charlie Brown",
        estimatedHours: 80,
        totalHoursLog: 60,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/gamma",
        freelanceComProfileLink: "https://www.freelancer.com/u/charliebrown",
        members: ["David White", "Eva Green", "Frank Black"],
        startDate: "2023-03-10",
      },
      {
        slNo: 4,
        client: "Client D",
        projectName: "Project Delta",
        projectValue: 1000,
        dealClosedBy: "David White",
        estimatedHours: 50,
        totalHoursLog: 40,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/delta",
        freelanceComProfileLink: "https://www.freelancer.com/u/davidwhite",
        members: ["Eva Green", "Frank Black", "Grace Taylor"],
        startDate: "2023-04-05",
      },
      {
        slNo: 5,
        client: "Client E",
        projectName: "Project Epsilon",
        projectValue: 1500,
        dealClosedBy: "Eva Green",
        estimatedHours: 70,
        totalHoursLog: 55,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/epsilon",
        freelanceComProfileLink: "https://www.freelancer.com/u/evagreen",
        members: ["Frank Black", "Grace Taylor", "Hank Miller"],
        startDate: "2023-05-20",
      },
      {
        slNo: 6,
        client: "Client F",
        projectName: "Project Zeta",
        projectValue: 2000,
        dealClosedBy: "Frank Black",
        estimatedHours: 90,
        totalHoursLog: 75,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/zeta",
        freelanceComProfileLink: "https://www.freelancer.com/u/frankblack",
        members: ["Grace Taylor", "Hank Miller", "Ivy Wilson"],
        startDate: "2023-06-15",
      },
      {
        slNo: 7,
        client: "Client G",
        projectName: "Project Eta",
        projectValue: 1800,
        dealClosedBy: "Grace Taylor",
        estimatedHours: 75,
        totalHoursLog: 65,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/eta",
        freelanceComProfileLink: "https://www.freelancer.com/u/gracetaylor",
        members: ["Hank Miller", "Ivy Wilson", "Jack Davis"],
        startDate: "2023-07-10",
      },
      {
        slNo: 8,
        client: "Client H",
        projectName: "Project Theta",
        projectValue: 2500,
        dealClosedBy: "Hank Miller",
        estimatedHours: 110,
        totalHoursLog: 90,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/theta",
        freelanceComProfileLink: "https://www.freelancer.com/u/hankmiller",
        members: ["Ivy Wilson", "Jack Davis", "Karen Moore"],
        startDate: "2023-08-25",
      },
      {
        slNo: 9,
        client: "Client I",
        projectName: "Project Iota",
        projectValue: 3000,
        dealClosedBy: "Ivy Wilson",
        estimatedHours: 120,
        totalHoursLog: 100,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/iota",
        freelanceComProfileLink: "https://www.freelancer.com/u/ivywilson",
        members: ["Jack Davis", "Karen Moore", "Liam Johnson"],
        startDate: "2023-09-20",
      },
      {
        slNo: 10,
        client: "Client J",
        projectName: "Project Kappa",
        projectValue: 2200,
        dealClosedBy: "Jack Davis",
        estimatedHours: 95,
        totalHoursLog: 80,
        freelanceComMessagePageLink:
          "https://www.freelancer.com/messages/project/kappa",
        freelanceComProfileLink: "https://www.freelancer.com/u/jackdavis",
        members: ["Karen Moore", "Liam Johnson", "Mia Anderson"],
        startDate: "2023-10-15",
      },
    ],
  },
];
